core/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('erp.urls', namespace='erp')),

    path('admin/', admin.site.urls),
]

erp/urls.py
from django.urls import path
from erp import views

app_name = 'erp'

urlpatterns = [
    # GET /
    path('', views.HomeView.as_view(), name="index"),

    # GET /funcionarios
    path('funcionarios/', views.HomeFuncionarioView.as_view(), name="index_funcionarios"),

    # GET /funcionarios/cadastrar
    path('funcionarios/cadastrar', views.CriaFuncionarioView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    path('funcionarios/lista', views.ListaFuncionariosView.as_view(), name="lista_funcionarios"),

    # GET/POST /funcionarios/{pk}
    path('funcionarios/<pk>', views.AtualizaFuncionarioView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionarios/excluir/<pk>', views.DeletaFuncionarioView.as_view(), name="deleta_funcionario"),

    # GET /produtos
    path('produtos/', views.HomeProdutoView.as_view(), name="index_produtos"),

    # GET /produtos/cadastrar
    path('produtos/cadastrar', views.CriaProdutoView.as_view(), name="cadastra_produto"),

    # GET /produtos
    path('produtos/lista', views.ListaProdutosView.as_view(), name="lista_produtos"),

    # GET/POST /produtos/{pk}
    path('produtos/<pk>', views.AtualizaProdutoView.as_view(), name="atualiza_produto"),

    # GET/POST /produtos/excluir/{pk}
    path('produtos/excluir/<pk>', views.DeletaProdutoView.as_view(), name="deleta_produto"),

    # GET /vendas
    path('vendas/', views.HomeVendaView.as_view(), name="index_vendas"),

    # GET /vendas/cadastrar
    path('vendas/cadastrar', views.CriaVendaView.as_view(), name="cadastra_venda"),

    # GET /vendas
    path('vendas/lista', views.ListaVendasView.as_view(), name="lista_vendas"),

    # GET/POST /vendas/{pk}
    path('vendas/<pk>', views.AtualizaVendaView.as_view(), name="atualiza_venda"),

    # GET/POST /vendas/excluir/{pk}
    path('vendas/excluir/<pk>', views.DeletaVendaView.as_view(), name="deleta_venda"),
]

erp/forms.py
from core.models import Funcionario, Produto, Venda
from django import forms


# FORMULÁRIO DE INCLUSÃO DE FUNCIONÁRIOS
# -------------------------------------------

class InsereFuncionarioForm(forms.ModelForm):

    chefe = forms.BooleanField(
        label='Chefe?',
        required=False,
    )

    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    class Meta:
        # Modelo base
        model = Funcionario

        # Campos que estarão no form
        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'tempo_de_servico',
            'remuneracao'
        ]


# FORMULÁRIO DE INCLUSÃO DE Produtos
# -------------------------------------------

class InsereProdutoForm(forms.ModelForm):
    descricao = forms.CharField(
        label='Descrição',
        required=True,
        widget=forms.Textarea
    )

    class Meta:
        # Modelo base
        model = Produto

        # Campos que estarão no form
        fields = [
            'nome',
            'descricao',
            'preco'
        ]


# FORMULÁRIO DE INCLUSÃO DE Vendas
# -------------------------------------------

class InsereVendaForm(forms.ModelForm):
    class Meta:
        # Modelo base
        model = Venda

        # Campos que estarão no form
        fields = [
            'funcionario',
            'produto'
        ]

erp/views.py
from django.db.models import Sum
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from core.models import Funcionario, Produto, Venda
from erp.forms import InsereFuncionarioForm, InsereProdutoForm, InsereVendaForm


# PÁGINA PRINCIPAL
# ----------------------------------------------

class HomeView(TemplateView):
    template_name = "erp/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data()

        context['vendas'] = Venda.objetos.all()
        
        # Soma de vendas por funcionário
        context['vendas_funcionario'] = \
            Venda.objetos.values('funcionario__nome').annotate(
                numero_vendas=Sum('produto'),
                total_vendas=Sum('produto__preco'),
                media_venda=Sum('produto__preco')/Sum('produto')
            )

        # Total em vendas
        context['total_vendas'] = Venda.objetos.aggregate(vendas=Sum('produto__preco'))

        # Quantidade total de vendas
        context['qtde_vendas'] = Venda.objetos.count()

        return context


# PÁGINA PRINCIPAL FUNCIONÁRIOS
# ----------------------------------------------

class HomeFuncionarioView(TemplateView):
    template_name = "erp/funcionarios/index.html"


# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class ListaFuncionariosView(ListView):
    template_name = "erp/funcionarios/lista.html"
    model = Funcionario
    context_object_name = "funcionarios"


# CADASTRAMENTO DE FUNCIONÁRIOS
# ----------------------------------------------

class CriaFuncionarioView(CreateView):
    template_name = "erp/funcionarios/cria.html"
    model = Funcionario
    form_class = InsereFuncionarioForm
    success_url = reverse_lazy("erp:lista_funcionarios")


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class AtualizaFuncionarioView(UpdateView):
    template_name = "erp/funcionarios/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("erp:lista_funcionarios")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class DeletaFuncionarioView(DeleteView):
    template_name = "erp/funcionarios/exclui.html"
    model = Funcionario
    context_object_name = 'funcionario'
    success_url = reverse_lazy("erp:lista_funcionarios")


# PÁGINA PRINCIPAL PRODUTOS
# ----------------------------------------------

class HomeProdutoView(TemplateView):
    template_name = "erp/produtos/index.html"


# LISTA DE PRODUTOS
# ----------------------------------------------

class ListaProdutosView(ListView):
    template_name = "erp/produtos/lista.html"
    model = Produto
    context_object_name = "produtos"


# CADASTRAMENTO DE PRODUTOS
# ----------------------------------------------

class CriaProdutoView(CreateView):
    template_name = "erp/produtos/cria.html"
    model = Produto
    form_class = InsereProdutoForm
    success_url = reverse_lazy("erp:lista_produtos")


# ATUALIZAÇÃO DE PRODUTOS
# ----------------------------------------------

class AtualizaProdutoView(UpdateView):
    template_name = "erp/produtos/atualiza.html"
    model = Produto
    fields = '__all__'
    context_object_name = 'produto'
    success_url = reverse_lazy("erp:lista_produtos")


# EXCLUSÃO DE PRODUTOS
# ----------------------------------------------

class DeletaProdutoView(DeleteView):
    template_name = "erp/produtos/exclui.html"
    model = Produto
    context_object_name = 'produto'
    success_url = reverse_lazy("erp:lista_produtos")


# PÁGINA PRINCIPAL VENDAS
# ----------------------------------------------

class HomeVendaView(TemplateView):
    template_name = "erp/vendas/index.html"


# LISTA DE VENDAS
# ----------------------------------------------

class ListaVendasView(ListView):
    template_name = "erp/vendas/lista.html"
    model = Venda
    context_object_name = "vendas"


# CADASTRAMENTO DE VENDAS
# ----------------------------------------------

class CriaVendaView(CreateView):
    template_name = "erp/vendas/cria.html"
    model = Venda
    form_class = InsereVendaForm
    success_url = reverse_lazy("erp:cadastra_venda")


# ATUALIZAÇÃO DE VENDAS
# ----------------------------------------------

class AtualizaVendaView(UpdateView):
    template_name = "erp/vendas/atualiza.html"
    model = Venda
    fields = '__all__'
    context_object_name = 'venda'
    success_url = reverse_lazy("erp:lista_vendas")


# EXCLUSÃO DE VENDAS
# ----------------------------------------------

class DeletaVendaView(DeleteView):
    template_name = "erp/vendas/exclui.html"
    model = Venda
    context_object_name = 'venda'
    success_url = reverse_lazy("erp:lista_vendas")

erp/templates/erp/vendas/atualiza.html
{% extends "erp/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Venda{% endblock %}

{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Atualizar Dados de Venda</h5>
                        <form method="post">
                            <!-- Não se esqueça dessa tag -->
                            {% csrf_token %}

                            <!-- Funcionário -->
                            <div class="input-group mb-3">
                                <span class="input-group-text">Funcionário</span>
                                {% render_field form.funcionario class+="form-control" %}
                            </div>

                            <!-- Produto -->
                            <div class="input-group mb-3">
                                <span class="input-group-text">Produto</span>
                                {% render_field form.produto class+="form-control" %}
                            </div>

                            <hr/>
                            <div class="text-end">
                                <a href="{% url 'erp:lista_vendas' %}" class="btn btn-outline-primary">Voltar</a>
                                <button class="btn btn-primary">Enviar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

erp/templates/erp/vendas/cria.html
{% extends "erp/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Venda{% endblock %}

{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cadastro de Venda</h5>
                        <p class="card-text">Complete o formulário abaixo para cadastrar um novo <code>Venda</code>.</p>
                        <form method="post">
                            <!-- Não se esqueça dessa tag -->
                            {% csrf_token %}

                            <!-- Funcionário -->
                            <div class="input-group mb-3">
                                <span class="input-group-text">Funcionário</span>
                                {% render_field form.funcionario class+="form-control" %}
                            </div>

                            <!-- Produto -->
                            <div class="input-group mb-3">
                                <span class="input-group-text">Produto</span>
                                {% render_field form.produto class+="form-control" %}
                            </div>
                            <hr>
                            <div class="text-end">
                                <a href="{% url 'erp:index' %}" class="btn btn-outline-primary">Voltar</a>
                                <button class="btn btn-primary">Enviar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

erp/templates/erp/vendas/exclui.html
<!-- Estendemos do template base -->
{% extends "erp/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Exclusão de Vendas</h5>

                <p class="card-text">
                    Você tem certeza que quer excluir o registro de venda <b>{{ venda.id }} feita
                    por {{ venda.funcionario.nome }}</b>?
                </p>

                <form method="post">
                    {% csrf_token %}

                    <hr/>
                    <div class="text-end">
                        <a href="{% url 'erp:lista_vendas' %}" class="btn btn-outline-danger">
                            Cancelar
                        </a>
                        <button class="btn btn-danger">Excluir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

erp/templates/erp/vendas/index.html
<!-- Estendemos do template base -->
{% extends "erp/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Venda</h5>
          <p class="card-text">Cadastre aqui um novo registro de <code>Venda</code>.</p>
          <a href="{% url 'erp:cadastra_venda' %}" class="btn btn-primary">Nova Venda</a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Vendas</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Vendas</code> registradas.
          </p>
          <a href="{% url 'erp:lista_vendas' %}" class="btn btn-primary">Vá para Lista</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

erp/templates/erp/vendas/lista.html
{% extends "erp/_layouts/base.html" %}

{% block title %}Lista de Funcionários{% endblock %}

{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card border-dark">
                    <div class="card-header"><b>Lista de Vendas Registradas</b></div>
                    <div class="card-body">
                        {% if vendas|length > 0 %}
                            <p class="card-text">Aqui está a lista de <code><b>Vendas</b></code> registradas.</p>

                            <table class="table table-light table-striped table-hover align-middle">
                                <thead>
                                <tr>
                                    <th scope="col">Funcionário</th>
                                    <th scope="col">Produto</th>
                                    <th scope="col">Preço</th>
                                    <th scope="col" class="text-center">Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for venda in vendas %}
                                    <tr>
                                        <td>{{ venda.funcionario.nome }}</td>
                                        <td>{{ venda.produto.nome }}</td>
                                        <td>R$ {{ venda.produto.preco }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'erp:atualiza_venda' pk=venda.id %}"
                                               class="btn btn-primary btn-sm">Atualizar</a>
                                            <a href="{% url 'erp:deleta_venda' pk=venda.id %}" class="btn btn-danger btn-sm">Excluir</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <div class="text-center mt-5 mb-5 jumbotron">
                                <h5>Nenhum <code>Venda</code> registrada ainda.</h5>
                            </div>
                        {% endif %}
                        <hr/>
                        <div class="text-end">
                            <a href="{% url 'erp:cadastra_venda' %}" class="btn btn-primary btn-sm">Cadastrar Venda</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}